<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{f88a4a61-b782-4030-a966-b2f336fe2bbe}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	SampleDevice : UDINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SampleDevice := SampleDevice + 1;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>